@startuml
if (Less than 8 characters and entirely numeric?) then (yes)
        :Password is very weak.;
        stop
else (no)
    if (Less than 8 characters or entirely numeric?) then (yes)
        :Password is weak.;
        stop
    else (no)
        if (Contains >= 1 number and >= 1 letter and >= 1 special character?) then (yes)
           :Password is very strong.;
           stop
        else (no)
            if (Contains >= 1 letter and >= 1 special character or Contains >= number?) then (yes)
                :Password is strong.;
                stop
            else (no)
                :Password is good.;
                stop
            endif
        endif
    endif
endif
@enduml